version: "3"
services:
  app:
    container_name: books-app
    build:
      context: .
      target: ${FRONTEND_BUILD_TARGET:-dev} # use "prod" for production
      # use when building for production
      #args:
      #  REACT_APP_BASE_API: ${BACKEND_URL:-http://localhost:9091}
    environment:
      REACT_APP_BASE_API: ${BACKEND_URL:-http://localhost:9091}
    volumes:
      - .:/var/www/frontend:delegated
    ports:
      - "8080:8080"
