version: "3"
services:
  app:
    container_name: angular-books-app
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: ${FRONTEND_BUILD_TARGET:-dev} # use "prod" for production
      # use when building for production
      #args:
      #  API_URL: ${BACKEND_URL:-http://localhost:9091}
    environment:
      API_URL: ${BACKEND_URL:-http://localhost:9091}
    volumes:
      - ./../:/var/www/frontend:delegated
    ports:
      - "8080:8080"
